# === DO_NOT_EDIT: pkg-ext site ===
site_name: pkg_ext
# === OK_EDIT: pkg-ext site ===

# === DO_NOT_EDIT: pkg-ext theme ===
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
# === OK_EDIT: pkg-ext theme ===

# === DO_NOT_EDIT: pkg-ext nav ===
nav:
  - Home: index.md
  - pkg_ext:
    - Overview: _root/index.md
    - PkgSettings: _root/pkgsettings.md
  - api_commands: api_commands/index.md
  - api_dump:
    - Overview: api_dump/index.md
    - CLICommandDump: api_dump/clicommanddump.md
    - CLIParamInfo: api_dump/cliparaminfo.md
    - CallableSignature: api_dump/callablesignature.md
    - ClassDump: api_dump/classdump.md
    - ClassFieldInfo: api_dump/classfieldinfo.md
    - ExceptionDump: api_dump/exceptiondump.md
    - FuncParamInfo: api_dump/funcparaminfo.md
    - FunctionDump: api_dump/functiondump.md
    - GlobalVarDump: api_dump/globalvardump.md
    - GroupDump: api_dump/groupdump.md
    - ParamDefault: api_dump/paramdefault.md
    - ParamKind: api_dump/paramkind.md
    - PublicApiDump: api_dump/publicapidump.md
    - TypeAliasDump: api_dump/typealiasdump.md
  - changelog: changelog/index.md
  - generate: generate/index.md
  - stability: stability/index.md
  - workflows: workflows/index.md
# === OK_EDIT: pkg-ext nav ===

# === DO_NOT_EDIT: pkg-ext extensions ===
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - attr_list
# === OK_EDIT: pkg-ext extensions ===
