# path-sync copy -n python-template
name: 'Post Merge'
run-name: 'Create a new tag for the release'

on:
  push:
    branches: 
    - "main"
    paths:
    - ".changelog/*"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: post-merge
        run: just pkg-post-merge
      - name: Get the tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
      - name: Trigger Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run release.yaml --ref ${{ steps.get_tag.outputs.tag }} -f tag=${{ steps.get_tag.outputs.tag }}
      - name: Trigger Docs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run docs.yaml --ref main
